/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function downloadWallpaper(url: string, savePath: string, detailPageUrl?: string | undefined | null): Promise<string>

export interface ScrapeResult {
  wallpapers: Array<WallpaperInfo>
  pageTitle: string
  totalFound: number
  errors: Array<string>
}

export declare function scrapeUrl(url: string, pagesToScrape: number): Promise<ScrapeResult>

export interface WallpaperInfo {
  thumbnailUrl: string
  fullUrl: string
  alt: string
  width?: number
  height?: number
  /** The URL of the detail/single-wallpaper page, used for fallback resolution discovery */
  detailPageUrl?: string
}
